services:
  deezer-addon:
    #image: ghcr.io/2t0m/deezer-eclipse-addon:main
    image: deezer-eclipse-addon:latest
    container_name: deezer-eclipse-addon
    restart: unless-stopped
    environment:
      - DEEZER_ARL=${DEEZER_ARL}
      - API_KEY=${API_KEY}
      - PORT=3000
      - TZ=${TZ:-Europe/Paris}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    ports:
      - "3000:3000"
    networks:
      - npm-network

networks:
  npm-network:
    external: true